---
- hosts: localhost
  gather_facts: no
  vars:
    region: ap-southeast-2
    name: test
  tasks:
    - name: get instance id
      instance_lookup:
        region: "{{ region }}"
        tags:
          env: "{{ name }}"
      register: instanceid

    - debug: var=instanceid.instance_ids

    - name: stop instance
      ec2:
        region: "{{ region }}"
        instance_ids: "{{ instanceid.instance_ids }}"
        state: stopped
        wait: yes
      when: instanceid is defined

